### ISSUE TITLE
Make react component bootstrapping pluggable

### ISSUE THREAD

**Issue by dennari** [lucified/lucify-component-builder#28]
The only React specific thing in `lucify-component-builder` is the feature that _[bootstraps](https://github.com/lucified/lucify-component-builder/blob/master/src/js/react-bootstrap/bootstrap-component.jsx)_ the component. What this means in practice is that it wraps it with the `EmbedWithUrlParamsDecorator` and then actually renders it into the DOM.

This feature includes code that would need updating once we move to newer React versions. I suggest we use this as an opportunity to refactor the bootstrapping code away from `lucify-component-builder` so that it won't be React specific anymore.

**Comment by juhoojala** [comment]
As of https://github.com/lucified/lucify-component-builder/pull/39 lucify-component-builder is no more specific to React
